[build]
builder = "DOCKERFILE"
dockerfilePath = "./docker/Dockerfile"

[deploy]
startCommand = ""  # Not needed as nginx starts automatically
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "80" 