version: '3.8'
services:
  db_test:
    image: postgres:latest
    container_name: ligenia_db_test
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  db_test_data: 