// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kytlaqdijkfwknxnrvma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dGxhcWRpamtmd2tueG5ydm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTgxMzMsImV4cCI6MjA1NzUzNDEzM30.6jtBNNXT09P96ChvOYc0AB6Fs1yySrwlwyqvBI6QumA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);