// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { config } from '@/config';

// Validate required Supabase configuration
if (!config.supabaseUrl || !config.supabaseAnonKey) {
  const missingVars = [];
  if (!config.supabaseUrl) missingVars.push('VITE_SUPABASE_URL');
  if (!config.supabaseAnonKey) missingVars.push('VITE_SUPABASE_ANON_KEY');
  
  const errorMessage = `Missing required Supabase environment variables: ${missingVars.join(', ')}`;
  console.error(errorMessage);
  
  if (config.isProduction) {
    throw new Error(errorMessage);
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  config.supabaseUrl || '',
  config.supabaseAnonKey || ''
);